export default function AIJobRecommendationPage() {
  const jobs = [
    {
      title: "Senior Full Stack Developer",
      score: "95%",
      salary: "LKR 450,000",
      skills: ["React", "ASP.NET", "SQL Server"],
    },
    {
      title: "Backend Developer",
      score: "91%",
      salary: "LKR 350,000",
      skills: ["C#", ".NET", "PostgreSQL"],
    },
    {
      title: "Frontend Engineer",
      score: "89%",
      salary: "LKR 300,000",
      skills: ["React", "TypeScript", "Tailwind"],
    },
    {
      title: "QA Automation Engineer",
      score: "86%",
      salary: "LKR 280,000",
      skills: ["Selenium", "Playwright", "C#"],
    },
    {
      title: "DevOps Engineer",
      score: "84%",
      salary: "LKR 400,000",
      skills: ["Azure", "Docker", "Kubernetes"],
    },
    {
      title: "Data Analyst",
      score: "80%",
      salary: "LKR 250,000",
      skills: ["Python", "Power BI", "SQL"],
    },
  ];

  return (
    <div className="p-8 bg-slate-50 min-h-screen">
      <h1 className="text-4xl font-bold">
        AI Job Recommendations
      </h1>

      <p className="text-slate-500 mt-2">
        Personalized job recommendations generated by AI.
      </p>

      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6 mt-8">
        {jobs.map((job) => (
          <div
            key={job.title}
            className="bg-white rounded-2xl border p-6 shadow-sm hover:shadow-md transition"
          >
            <div className="flex justify-between items-center">
              <h2 className="text-lg font-semibold">
                {job.title}
              </h2>

              <span className="bg-blue-100 text-blue-700 px-3 py-1 rounded-full text-sm">
                {job.score}
              </span>
            </div>

            <p className="text-slate-600 mt-4">
              Salary: {job.salary}
            </p>

            <div className="mt-4">
              <p className="font-medium mb-2">
                Required Skills
              </p>

              <div className="flex flex-wrap gap-2">
                {job.skills.map((skill) => (
                  <span
                    key={skill}
                    className="bg-slate-100 px-3 py-1 rounded-full text-sm"
                  >
                    {skill}
                  </span>
                ))}
              </div>
            </div>

            <button className="w-full mt-6 bg-indigo-600 text-white py-2 rounded-lg hover:bg-indigo-700 transition">
              View Details
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}